# Cloud Build configuration for SpendShield AI
# This file defines how to build and deploy the application to Cloud Run

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/spendshield-ai:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/spendshield-ai:latest'
      - '.'
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/spendshield-ai:$COMMIT_SHA'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/spendshield-ai:latest'
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'spendshield-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/spendshield-ai:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PORT=8080,UPLOAD_DIR=/tmp/uploads'

images:
  - 'gcr.io/$PROJECT_ID/spendshield-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/spendshield-ai:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
